# Site settings
title: AIAH'S BLOG
SEOTitle: Aiah的博客 | Aiah's Blog
header-img: img/post-bg-desk.jpg
email: aiahwang@163.com
description: "Every failure is leading towards success."
keyword: "AIAH'S BLOG, Aiah的博客, NLP, text summarization, abstractive summarization, multi-document summarization, text generation"
url: "http://aiah.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/aiah/aiah.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I Love NLP!"
sidebar-avatar: /img/about-myself.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     我叫爱码士
zhihu_username:     Aiah
github_username:    aiah
facebook_username:  王烨
jianshu_username:   846a01695435
#twitter_username:   aiah




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7d468c0344cf414ab844                            #生成的clientID
  clientSecret: 7f7da1309302d8ab8757e853f620f37e02a5a8b3    #生成的clientSecret
  repo: aiah.github.io    #仓库名称
  owner: aiah    #github用户名
  admin: aiah
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 786f2ea6528ffe5f3b1e2d7fff6215ca

# Google Analytics
ga_track_id: 'UA-176926663-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/846a01695435"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
